name: ğŸš€ Pipeline Principal via workflow externo

on:
  push:
    branches:
      - staging

jobs:
  call-main-workflow:
    name: ğŸ” Executando workflow principal
    uses: felipe-domingues/workflows-base/.github/workflows/main.yml
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
