name: ğŸš€ Pipeline Principal via workflow externo

on:
  push:
    branches:
      - staging

jobs:
  call-main-workflow:
    name: ğŸ” Executando workflow principal
    uses: Felipe-Domingues/workflows-base/.github/workflows/main.yml@d1f7e7b267d3425618611d75d0551b52fc69ae10
    secrets: inherit
