name: ğŸš€ Pipeline Principal via workflow externo

on:
  push:
    branches:
      - staging

jobs:
  call-main-workflow:
    name: ğŸ” Executando workflow principal
    uses: ./.github/workflows/main.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
