name: 游 Pipeline Principal via workflow externo

on:
  push:
    branches:
      - staging

jobs:
  call-main-workflow:
    name: 游대 Executando workflow principal
    uses: felipe-domingues/workflows-base/.github/workflows/main.yml@main
    with:
      # Passe vari치veis necess치rias para o workflow reutilizado, se necess치rio.
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    secrets:
      # Adicione qualquer segredo necess치rio.
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
