name: ğŸš€ Pipeline Principal via workflow externo

on:
  push:
    branches:
      - staging

jobs:
  call-main-workflow:
    name: ğŸ” Executando workflow principal
    uses: https://github.com/Felipe-Domingues/workflows-base/blob/b1dd573f5b45d23774b6bbcd5917441960eb2ab6/.github/workflows/main.yml
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
