name: ğŸš€ Production Workflow

on:
  workflow_dispatch:

jobs:
  build-production:
    name: ğŸ§ª Testes de ProduÃ§Ã£o
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ” Rodando verificaÃ§Ã£o final
        run: |
          echo -e "\033[1;35mğŸš¢ Executando testes no ambiente de produÃ§Ã£o...\033[0m"
          sleep 2
          echo -e "\033[1;32mâœ… ProduÃ§Ã£o verificada com sucesso!\033[0m"
